pragma Singleton

// island-dots. GPL-3.0 — see LICENSE.

import Quickshell

// Every path the shell reads or writes, in one place.
//
// Nothing here points into the repo, and nothing hardcodes the clone
// directory: generated files live under the state directory and the
// machine-specific matugen config is written by install.sh, so the
// shell never needs to know where the repo is.
Singleton {
    id: root

    readonly property string home: Quickshell.env("HOME")

    // Quickshell.env returns an empty string for an unset variable
    // rather than undefined, so an `||` chain would still pick it.
    function xdg(name, fallback) {
        const v = Quickshell.env(name);
        return (v && v.length > 0) ? v : root.home + fallback;
    }

    readonly property string configHome: xdg("XDG_CONFIG_HOME", "/.config")
    readonly property string stateHome:  xdg("XDG_STATE_HOME",  "/.local/state")
    readonly property string cacheHome:  xdg("XDG_CACHE_HOME",  "/.cache")

    readonly property string configDir: configHome + "/island"
    readonly property string stateDir:  stateHome + "/island"

    readonly property string settings:  configDir + "/settings.json"

    // Written by install.sh with absolute paths filled in, because
    // matugen's TOML cannot expand a variable.
    readonly property string matugenConfig: configDir + "/matugen.toml"

    // Generated by matugen on every wallpaper change. Kept out of the
    // repo: it is machine state, and a checkout is not writable on
    // every machine the shell might run on.
    readonly property string colors:    stateDir + "/colors.json"
    readonly property string wallpaper: stateDir + "/wallpaper"

    // The terminal, file manager and browser the Super+X/E/B binds
    // spawn, as a Lua table for hypr/env.lua to overlay onto its own.
    //
    // Generated rather than edited in place, and here rather than in
    // the repo, for the reason at the top of this file plus one more:
    // install.sh symlinks ~/.config/hypr to the checkout, so a
    // settings window that wrote to env.lua would put a diff in
    // `git status` every time somebody changed their browser.
    readonly property string apps: stateDir + "/apps.lua"
}
